[build-system]
requires = ["setuptools",
            "aiohttp",
            "pydantic",
            "typing"]
build-backend = "setuptools.build_meta"

[tool.black]
target-version = ["py36", "py37", "py38", "py39", "py310"]