name: Python package

on:
  pull_request:
    branches:
      - '**'

env:
  API_KEY: ${{secrets.CAPMONSTERCLOUD_CLIENTKEY}}

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"] # asyncio isolated unittest work >= 3.8
      
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
      - name: Running tests
        run: |
          . run_tests.sh